### ISSUE TITLE
Hiding stuff in documentation

### ISSUE THREAD

**Issue by agraven** [ExpHP/newtype-ops#2]
Hi. Just wanted to let you know you can prevent stuff from appearing in the documentation with the `#[doc(hidden)]` attribute. You can read more about it in the [rustdoc documentation](https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#dochidden).

Happy hacking!

**Comment by ExpHP** [comment]
Oops, silly me. Not sure why I didn't do that.  Done now on 0dc6844d703a255b6e2b3d394065174393581d5a.

On a related note, this entire crate is probably broken in 2018 edition thanks to that helper macro.  For this I created #3.
